version: "3"

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /app-frontend
    platform: linux/x86_64
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    image: node:16
    container_name: backend
    build: ./backend
    ports:
      - 3001:3001
    working_dir: /app-backend
    volumes:
      - ./:/app
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/WebScraper
    networks:
      - web_scraper_net

  mongodb:
    image: mongo:5.0.7
    container_name: mongo_db
    volumes:
      - ./:/app
    restart: always
    ports:
      - 27017:27017
    networks:
      - web_scraper_net

  chrome:
    image: selenium/standalone-chrome
    container_name: selenium-chrome
    shm_size: 2g
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

networks:
  web_scraper_net:
    driver: bridge
